module.exports = {
  filetypes: {
    ".LOG": "Log File",
    ".MSG": "Outlook Mail Message",
    ".ODT": "OpenDocument Text Document",
    ".PAGES": "Pages Document",
    ".RTF": "Rich Text Format File",
    ".TEX": "LaTeX Source Document",
    ".TIF": "GeoTIFF Image",
    ".TIFF": "Tagged Image File Format",
    ".TXT": "Plain Text File",
    ".WPD": "WordPerfect Document",
    ".WPS": "Kingsoft Writer Document",
    ".CSV": "Comma Separated Values File",
    ".DAT": "Exchange E-mail Attachment",
    ".GED": "GEDCOM Genealogy Data File",
    ".KEY": "Keynote Presentation",
    ".KEYCHAIN": "Mac OS X Keychain File",
    ".PPS": "PowerPoint Slide Show",
    ".PPT": "PowerPoint Presentation",
    ".PPTX": "PowerPoint Open XML Presentation",
    ".SDF": "Structure Data File",
    ".TAR": "Consolidated Unix File Archive",
    ".TAX2016": "TurboTax 2016 Tax Return",
    ".TAX2017": "TurboTax 2017 Tax Return",
    ".TAX2018": "TurboTax 2018 Tax Return",
    ".TAX2019": "TurboTax 2019 Tax Return",
    ".TAX2020": "TurboTax 2020 Tax Return",
    ".TAX2021": "TurboTax 2021 Tax Return",
    ".TAX2022": "TurboTax 2022 Tax Return",
    ".VCF": "vCard File",
    ".XML": "XML File",
    ".AIF": "Audio Interchange File Format",
    ".IFF": "Interchange File Format",
    ".M3U": "Media Playlist File",
    ".M4A": "MPEG-4 Audio File",
    ".MID": "MIDI File",
    ".MP3": "MP3 Audio File",
    ".MPA": "MPEG-2 Audio File",
    ".WAV": "WAVE Audio File",
    ".WMA": "Windows Media Audio File",
    ".3G2": "3GPP2 Multimedia File",
    ".3GP": "3GPP Multimedia File",
    ".ASF": "Advanced Systems Format File",
    ".AVI": "Audio Video Interleave File",
    ".FLV": "Flash Video File",
    ".M4V": "iTunes Video File",
    ".MOV": "Apple QuickTime Movie",
    ".MP4": "MPEG-4 Video File",
    ".MPG": "MPEG Video File",
    ".RM": "RealMedia File",
    ".SRT": "SubRip Subtitle File",
    ".SWF": "Shockwave Flash Movie",
    ".VOB": "DVD Video Object File",
    ".WMV": "Windows Media Video File",
    ".3DM": "Rhino 3D Model",
    ".3DS": "3D Studio Scene",
    ".MAX": "PaperPort Scanned Document",
    ".BMP": "Bitmap Image File",
    ".DDS": "DirectDraw Surface",
    ".GIF": "Graphical Interchange Format File",
    ".HEIC": "High Efficiency Image Format",
    ".JPG": "JPEG Image",
    ".PNG": "Portable Network Graphic",
    ".PSD": "Adobe Photoshop Document",
    ".PSPIMAGE": "PaintShop Pro Image",
    ".TGA": "Targa Graphic",
    ".THM": "Thumbnail Image File",
    ".YUV": "YUV Encoded Image File",
    ".AI": "Adobe Illustrator File",
    ".EPS": "Encapsulated PostScript File",
    ".SVG": "Scalable Vector Graphics File",
    ".INDD": "Adobe InDesign Document",
    ".PCT": "Picture File",
    ".PDF": "Portable Document Format File",
    ".XLR": "Works Spreadsheet",
    ".XLS": "Excel Spreadsheet",
    ".XLSX": "Microsoft Excel Open XML Spreadsheet",
    ".ACCDB": "Access 2007 Database File",
    ".DB": "Database File",
    ".DBF": "Database File",
    ".MDB": "Microsoft Access Database",
    ".PDB": "Palm Desktop Database File",
    ".SQL": "Structured Query Language Data File",
    ".APK": "Android Package File",
    ".APP": "macOS Application",
    ".BAT": "DOS Batch File",
    ".CGI": "Common Gateway Interface Script",
    ".COM": "DOS Command File",
    ".EXE": "PortableApps.com Application",
    ".GADGET": "Windows Gadget",
    ".JAR": "Java Archive File",
    ".WSF": "Windows Script File",
    ".B": "Grand Theft Auto 3 Saved Game File",
    ".DEM": "Video Game Demo File",
    ".GAM": "Saved Game File",
    ".NES": "Nintendo (NES) ROM File",
    ".ROM": "N64 Game ROM File",
    ".SAV": "Mass Effect 3 Saved Game",
    ".DWG": "AutoCAD Drawing Database File",
    ".DXF": "Drawing Exchange Format File",
    ".GPX": "Guitar Pro 6 Document",
    ".KML": "Keyhole Markup Language File",
    ".KMZ": "Google Earth Placemark File",
    ".ASP": "Active Server Page",
    ".ASPX": "Active Server Page Extended File",
    ".CER": "Internet Security Certificate",
    ".CFM": "ColdFusion Markup File",
    ".CSR": "Certificate Signing Request File",
    ".CSS": "Cascading Style Sheet",
    ".DCR": "Shockwave Media File",
    ".HTM": "Hypertext Markup Language File",
    ".HTML": "Hypertext Markup Language File",
    ".JS": "JavaScript File",
    ".JSP": "Java Server Page",
    ".PHP": "PHP Source Code File",
    ".RSS": "Rich Site Summary",
    ".XHTML": "Extensible Hypertext Markup Language File",
    ".CRX": "Chrome Extension",
    ".PLUGIN": "Mac OS X Plugin",
    ".FNT": "Windows Font File",
    ".FON": "Generic Font File",
    ".OTF": "OpenType Font",
    ".TTF": "TrueType Font",
    ".CAB": "Windows Cabinet File",
    ".CPL": "Windows Control Panel Item",
    ".CUR": "Windows Cursor",
    ".DESKTHEMEPACK": "Windows 8 Desktop Theme Pack File",
    ".DLL": "Dynamic Link Library",
    ".DMP": "Windows Memory Dump",
    ".DRV": "Device Driver",
    ".ICNS": "macOS Icon Resource File",
    ".ICO": "Icon File",
    ".LNK": "Windows Shortcut",
    ".SYS": "Windows System File",
    ".CFG": "Configuration File",
    ".INI": "Windows Initialization File",
    ".PRF": "Windows System File",
    ".HQX": "BinHex 4.0 Encoded File",
    ".MIM": "Multi-Purpose Internet Mail Message File",
    ".UUE": "Uuencoded File",
    ".7Z": "7-Zip Compressed File",
    ".CBR": "Comic Book RAR Archive",
    ".DEB": "Debian Software Package",
    ".GZ": "Gnu Zipped Archive",
    ".PKG": "Mac OS X Installer Package",
    ".RAR": "WinRAR Compressed Archive",
    ".RPM": "Red Hat Package Manager File",
    ".SITX": "StuffIt X Archive",
    ".TAR.GZ": "Compressed Tarball File",
    ".ZIP": "MAME Game ROM",
    ".ZIPX": "Extended Zip File",
    ".BIN": "Binary Video File",
    ".CUE": "Cue Sheet File",
    ".DMG": "Apple Disk Image",
    ".ISO": "Disc Image File",
    ".MDF": "SQL Server Database File",
    ".TOAST": "Toast Disc Image",
    ".VCD": "Virtual CD",
    ".C": "C/C++ Source Code File",
    ".CLASS": "Java Class File",
    ".CPP": "C++ Source Code File",
    ".CS": "C# Source Code File",
    ".DTD": "Document Type Definition File",
    ".FLA": "Adobe Animate Animation",
    ".JAVA": "Java Source Code File",
    ".LUA": "Lua Source File",
    ".M": "Mathematica Input File",
    ".PL": "Perl Script",
    ".PY": "Python Script",
    ".SH": "Bash Shell Script",
    ".SLN": "Visual Studio Solution File",
    ".SWIFT": "Swift Source Code File",
    ".VB": "Visual Basic Project Item File",
    ".VCXPROJ": "Visual C++ Project",
    ".XCODEPROJ": "Xcode Project",
    ".BAK": "Backup File",
    ".TMP": "Temporary File",
    ".ICS": "Calendar File",
    ".MSI": "Windows Installer Package",
    ".PART": "Partially Downloaded File",
    ".TORRENT": "BitTorrent File",
    ".RFT": "Revisable Form Text Document",
    ".FCF": "Final Draft Converter File",
    ".SMF": "StarMath Formula File",
    ".APKG": "Exported Anki Flashcard Deck",
    ".LST": "Data List",
    ".FPT": "FoxPro Table Memo",
    ".OTT": "OpenDocument Document Template",
    ".FODT": "OpenDocument Flat XML Document",
    ".FDR": "Final Draft Document",
    ".MAN": "Unix Manual",
    ".ADOC": "AsciiDoc File",
    ".STY": "LaTeX Style",
    ".APT": "Almost Plain Text File",
    ".DIZ": "Description in Zip File",
    ".SAM": "Ami Pro Document",
    ".TEXT": "Plain Text File",
    ".UPD": "Program Update Information",
    ".AIM": "AIMMS ASCII Model File",
    ".RTX": "Rich Text Document",
    ".ANS": "ANSI Text File",
    ".EIO": "Yozo Office File",
    ".WTT": "Write! Document",
    ".FBL": "CADfix Command Level Log File",
    ".DROPBOX": "Dropbox Shared Folder Tracker",
    ".SAVE": "Nano Temporary Save File",
    ".ETF": "ENIGMA Transportable File",
    ".CHARSET": "Character Set",
    ".FAQ": "Frequently Asked Questions Document",
    ".MD5.TXT": "Message Digest 5 Hash File",
    ".MNT": "FoxPro Menu Memo",
    ".DOCM": "Word Open XML Macro-Enabled Document",
    ".LIS": "SQR Output File",
    ".LTX": "LaTeX Document",
    ".HS": "Java HelpSet File",
    ".SIG": "Signature File",
    ".ODM": "OpenDocument Master Document",
    ".GPD": "Generic Printer Description File",
    ".RPT": "Crystal Reports File",
    ".TEXTCLIPPING": "Mac OS X Text Clipping File",
    ".PWDPL": "Password Pad Lite Document",
    ".DOCZ": "ThinkFree Online Note Document",
    ".STORY": "Storyist Document",
    ".WP": "WordPerfect Document",
    ".IPF": "OS/2 Help File",
    ".WPW": "WP Works Word Processor File",
    ".LUE": "Norton LiveUpdate Log File",
    ".XY": "XYWrite Document",
    ".ASC": "ActionScript Communication File",
    ".VNT": "Mobile Phone vNote File",
    ".SAF": "Street Atlas USA Map File",
    ".TLB": "VAX Text Library",
    ".ME": "Readme Text File",
    ".TMDX": "TextMaker Document",
    ".1ST": "Readme File",
    ".OPEICO": "Opeico Text File",
    ".BDR": "Exchange Non-Delivery Report Body File",
    ".README": "Readme File",
    ".JARVIS": "Jarvis Subscriber File",
    ".KES": "Kurzweil 3000 Document",
    ".EIT": "Yozo Office Template File",
    ".RIS": "Research Information Systems Citation File",
    ".BIB": "BibTeX Bibliography Database",
    ".LP2": "iLEAP Word Processing Document",
    ".EML": "E-Mail Message",
    ".ATY": "Association Type Placeholder",
    ".LUF": "Lipikar Uniform Format File",
    ".DEL": "Delimited ASCII File",
    ".WPT": "WordPerfect Template",
    ".HWP": "Hangul (Korean) Text Document",
    ".KLG": "Log File",
    ".RAD": "Radar ViewPoint Radar Data",
    ".EPP": "EditPad Pro Project",
    ".FDX": "Final Draft Document",
    ".DXB": "Duxbury Braille File",
    ".TM": "TeXmacs Document",
    ".FADEIN.TEMPLATE": "Fade In Template",
    ".XYW": "XYWrite for Windows Document",
    ".IPSPOT": "iPhoto Spot File",
    ".ABW": "AbiWord Document",
    ".TMD": "TextMaker Document",
    "._DOCX": "Renamed Microsoft Word Open XML Document",
    ".NFO": "Warez Information File",
    ".RST": "reStructuredText File",
    ".RTFD": "Rich Text Format Directory File",
    ".RUN": "Runscanner Scan File",
    ".MBOX": "Email Mailbox File",
    ".AWW": "Ability Write Document",
    ".DVI": "Device Independent Format File",
    ".DSC": "Text Description File",
    ".ERR": "FoxPro Compilation Error",
    ".GSD": "General Station Description File",
    ".602": "Text602 Document",
    ".WRI": "Microsoft Write Document",
    ".SCM": "ScreenCam Screen Recording",
    ".STRINGS": "Text Strings File",
    ".FDT": "Final Draft 5-7 Template",
    ".LATEX": "LaTeX Document",
    ".PLAIN": "Plain Text File",
    ".CHORD": "Song Chords File",
    ".EMULECOLLECTION": "eMule Data File",
    ".EMLX": "Apple Mail Message",
    ".SCC": "Scenarist Closed Caption File",
    ".PWD": "Pocket Word Document",
    ".BEAN": "Bean Rich Text Document",
    ".JIS": "Japanese Industry Standard Text",
    ".DFTI": "FlexiWrite Document",
    ".FOUNTAIN": "Fountain Script File",
    ".SDM": "StarOffice Mail Message",
    ".U3I": "U3 Application Information File",
    ".DOCXML": "Microsoft Word XML Document",
    ".COD": "Atlantis Word Processor Encrypted Document",
    ".BIBTEX": "BibTeX Bibliography Database",
    ".NOTES": "Memento Notes File",
    ".NOW": "Readme File",
    ".KNT": "KeyNote Note File",
    ".STW": "StarOffice Document Template",
    ".HHT": "Help and Support Center HHT File",
    ".NOTE": "Notability Note File",
    ".XWP": "Crosstalk Session File",
    ".TEMPLATE": "Apple Pages Template",
    ".RVF": "RichView Format File",
    ".ODIF": "Open Document Interchange Format",
    ".JNP": "Java Web Start File",
    ".NGLOSS": "Nisus Writer Glossary",
    ".SE": "Shuttle Document",
    ".UTF8": "Unicode UTF8-Encoded Text Document",
    ".NDOC": "Naver Word",
    ".BDP": "Exchange Diagnostic Message",
    ".PWI": "Pocket Word Document",
    ".PSW": "Pocket Word Document",
    ".P7S": "Digitally Signed Email Message",
    ".QDL": "QDL Program",
    ".KON": "Yahoo! Widget XML File",
    ".JP1": "Japanese (Romaji) Text File",
    ".FRT": "FoxPro Report Memo",
    ".SLA": "Scribus Document",
    ".TAB": "MapInfo TAB File",
    ".IDX": "Movie Subtitle File",
    ".BAD": "Exchange Badmail File",
    ".MWD": "Mariner Write Document",
    ".SGM": "SGML File",
    ".BOC": "EasyWord Big Document",
    ".PVM": "Parallels Virtual Machine",
    ".WP7": "WordPerfect 7 Document",
    ".SCRIVX": "Scrivener XML Document",
    ".SCRIV": "Scrivener Document",
    ".TPC": "Topic Connection Placeholder",
    ".RZK": "File Crypt Password File",
    ".PRT": "Creo Parametric Part File",
    ".BNA": "Barna Word Processor Document",
    ".DX": "DEC WPS Plus File",
    ".RZN": "Red Zion Notes File",
    ".MWP": "Lotus Word Pro SmartMaster File",
    ".SLA.GZ": "Scribus Compressed Document",
    ".BML": "Braille 2000 Braille File",
    ".CALCA": "Calca Document",
    ".TRELBY": "Trelby File",
    ".SUBLIME-WORKSPACE": "Sublime Text Workspace File",
    ".SUBLIME-PROJECT": "Sublime Text Project File",
    ".SXW": "StarOffice Writer Document",
    ".HIGHLAND": "Highland Document",
    ".LICENSE": "Software License File",
    ".PIMX": "Adobe Package Installation Management File",
    ".PWR": "PowerWrite Document",
    ".LBT": "FoxPro Label Memo",
    ".MELLEL": "Mellel Word Processing Document",
    ".WP4": "WordPerfect 4 Document",
    ".SESSION": "Mozilla Firefox Session File",
    ".FDF": "Acrobat Forms Data Format",
    ".SDOC": "Satra Khmer Document",
    ".DCA": "DisplayWrite Document",
    ".ZRTF": "Nisus Compressed Rich Text File",
    ".MW": "Maple Worksheet",
    ".HBK": "Mathcad Handbook File",
    ".WBK": "WordPerfect Workbook",
    ".FLR": "Flare Decompiled ActionScript File",
    ".LXFML": "LEGO Digital Designer XML File",
    ".SMS": "Exported SMS Text Message",
    ".ZABW": "Compressed AbiWord Document File",
    ".ODO": "Online Operating System Write Document",
    ".CNM": "NoteMap Outline File",
    ".BTD": "Business-in-a-Box Document",
    "._DOC": "Renamed Microsoft Word Document",
    ".OFL": "Ots File List",
    ".PAGES-TEF": "Pages iCloud Document",
    ".JTD": "JustSystems Ichitaro Document",
    ".ACT": "FoxPro Documenting Wizard Action Diagram",
    ".OPENBSD": "OpenBSD Readme File",
    ".LYX": "LyX Document",
    ".SAFETEXT": "SafeText File",
    ".NJX": "NJStar Document",
    ".UOT": "Uniform Office Document",
    ".EUC": "Extended Unix Code File",
    ".HZ": "Chinese (Hanzi) Text",
    ".ORT": "Rich Text Editor Document",
    ".SSA": "Sub Station Alpha Subtitle File",
    ".XDL": "XML Schema File",
    ".DWD": "DavkaWriter File",
    ".BBS": "Bulletin Board System Text",
    ".ETX": "Structure Enhanced Text (Setext) File",
    ".WP6": "WordPerfect 6 Document",
    ".LTR": "Letter File",
    ".PMO": "Pegasus Saved Message File",
    ".PU": "PlantUML File",
    ".XBPLATE": "Xiosis Scribe Template",
    ".SXG": "Apache OpenOffice Master Document",
    ".RTD": "Robot Structural Analysis Design File",
    ".TDF": "Xserve Test Definition File",
    ".AWT": "AbiWord Template",
    ".FDXT": "Final Draft 8 Template",
    ".FWDN": "fWriter Document",
    ".TMV": "TimeMap Visual",
    ".WPL": "DEC WPS Plus Text Document",
    ".GV": "Graphviz DOT File",
    ".LWP": "Lotus Word Pro Document",
    ".SDW": "StarOffice Writer Text Document",
    ".DNE": "Netica Text File",
    ".CRWL": "Windows Crawl File",
    ".ASCII": "ASCII Text File",
    ".VCT": "Visual Class Library Memo",
    ".XYP": "XYWrite Plus Document",
    ".QUID": "QuidProQuo Document",
    ".DGS": "Dagesh Pro Document",
    ".XBDOC": "Xiosis Scribe Document",
    ".ASE": "Adobe Swatch Exchange File",
    ".UTXT": "Unicode Text File",
    ".SCT": "FoxPro Form Memo",
    ".LYT": "TurboTax Install Log File",
    ".NB": "Mathematica Notebook",
    ".UNAUTH": "SiteMinder Unauthorized Message File",
    ".GPN": "GlidePlan Map Document",
    ".WEBDOC": "Box.net Web Document",
    ".LNT": "Laego Note Taker File",
    ".QPF": "QuickPad Encrypted Document",
    ".WSD": "WordStar Document",
    ".GTHR": "Gather Log File",
    ".UNX": "Unix Text File",
    ".FDS": "Final Draft Secure Copy",
    ".EMF": "Enhanced Windows Metafile",
    ".SKCARD": "Starfish Sidekick Card File",
    ".XY3": "XYWrite III Document",
    ".NWM": "Nisus Macro",
    ".PWDP": "Password Pad Document",
    ".MELL": "Mellel Word Processing File",
    ".DXP": "Duxbury Print File",
    ".NWP": "Magentic Wallpaper File",
    ".PVJ": "ProofVision Job Ticket",
    ".AWP": "Ability Write Template",
    ".CYI": "Clustify Input File",
    ".FGS": "Fig Figure Settings File",
    ".WPA": "ACT! Word Processing Document",
    ".TMVX": "TextMaker Document Template",
    ".UOF": "Uniform Office Document",
    ".BRX": "Beam Report Document",
    ".QBL": "QuickBooks License File",
    ".KWD": "KWord Document",
    ".CWS": "Claris Works Template",
    ".WTX": "Text Document",
    ".ZW": "Chinese Text File",
    ".PFX": "PKCS #12 Certificate File",
    ".JRTF": "JAmes OS Rich Text File",
    ".PLANTUML": "PlantUML File",
    ".JOE": "JOE Document",
    ".MIN": "Mint Source File",
    ".WP5": "WordPerfect 5 Document",
    ".SCW": "Movie Magic Screenwriter Document",
    ".BZABW": "Compressed AbiWord Document",
    ".TVJ": "TrueView Job Ticket",
    ".VW": "Volkswriter Text File",
    ".NWCTXT": "NoteWorthy Composer Text File",
    ".PDPCMD": "Pdplayer Command File",
    ".IIL": "CleanSweep Installation Log",
    ".OCR": "FAXGrapper Fax Text File",
    ".GMD": "GroupMail Message",
    ".FFT": "Final Form Text File",
    ".DOX": "MultiMate Document",
    ".MCW": "MacWrite II Document",
    ".THP": "TurboTax Text String",
    ".WN": "WriteNow Text Document",
    ".DEK": "Magic: The Gathering Deck File",
    ".PSPBRUSH": "PaintShop Pro Brush File",
    ".ROADTRIP": "Road Trip Planner File",
    ".REP": "Grand Theft Auto Replay File",
    ".MYCOLORS": "Stardock MyColors Theme File",
    ".SIMS3PACK": "The Sims 3 Package File",
    ".SC2ASSETS": "Blizzard StarCraft 2 Assets File",
    ".W3N": "Warcraft 3 Expansion Campaign Map File",
    ".PCC": "Mass Effect Package",
    ".NBK": "NovaBACKUP Job File",
    ".TE": "Textease CT Database File",
    ".GBX": "Nadeo Game File",
    ".STB": "AutoCAD Plot Style Table File",
    ".TPZ": "Kindle Topaz eBook File",
    ".U10": "UFile 2010 Tax Return",
    ".NCORX": "Adobe Encore Project",
    ".H12": "At Home Canada 2012 Tax Return",
    ".PHJ": "PhCNC Project File",
    ".FMAT": "FMAT Runfile",
    ".PMX": "MikuMikuDance Model File",
    ".VPK": "Valve Pak",
    ".BLD": "Envisioneer Building Project File",
    ".ACROPLUGIN": "Adobe Acrobat Plug-in",
    ".DUF": "DAZ User File",
    ".UNITY3D": "Unity Web Player Archive",
    ".OSZ": "osu! Beatmap File",
    ".BZW": "BZFlag World File",
    ".AUX": "LaTeX Auxiliary File",
    ".UNITY": "Unity Scene File",
    ".SC2SAVE": "Blizzard StarCraft 2 Saved Game",
    ".REG": "Registry File",
    ".DMGPART": "Mac OS X Disk Image Part",
    ".W3X": "Warcraft 3 Expansion Map FIle",
    ".ASAX": "ASP.NET Server Application File",
    ".GBA": "Game Boy Advance ROM",
    ".DIF": "Data Interchange Format",
    ".TOR": "Star Wars: The Old Republic Asset File",
    ".HDF": "Hierarchical Data Format File",
    ".BLEND": "Blender 3D Data File",
    ".PCK": "System Center Configuration Manager Package File",
    ".LTF": "Laser App Temp Form File",
    ".CLP": "CrazyTalk Clip File",
    ".QUICKEN2015": "Quicken 2015 Data File",
    ".NDS": "Nintendo DS Game ROM",
    ".REZ": "Lithtech Game Engine Resource File",
    ".CMD": "Windows Command File",
    ".CRT": "Security Certificate",
    ".WZ": "MapleStory Game Data File",
    ".PACKAGE": "Electronic Arts Game Package File",
    ".A5W": "Alpha Five Webpage File",
    ".EDI": "Electronic Data Interchange File",
    ".SIMS3": "The Sims 3 Game Save File",
    ".CUB": "Analysis Services Cube File",
    ".MPKG": "Meta Package File",
    ".MDL": "Half-Life Model File",
    ".W3M": "Warcraft 3 Map File",
    ".STYLE": "SketchUp Style",
    ".THEMEPACK": "Windows 7 Theme Pack",
    ".FBW": "HP Recovery Manager Backup File",
    ".NBP": "Mathematica Player Notebook File",
    ".ANI": "Windows Animated Cursor",
    ".PRPROJ": "Premiere Pro Project",
    ".IV": "Open Inventor Scene Graph File",
    ".TDB": "Android Thumbnail Cache",
    ".CNF": "MySQL Configuration File",
    ".CRDOWNLOAD": "Chrome Partially Downloaded File",
    ".NOT": "Notation File",
    ".AW": "Answer Wizard File",
    ".UPK": "Unreal Engine 3 Package",
    ".RWZ": "Outlook Rules Wizard File",
    ".FCPEVENT": "Final Cut Pro Event File",
    ".BASH_HISTORY": "Bash History File",
    ".ESM": "Elder Scrolls Master File",
    ".WAD": "Doom WAD File",
    ".SMC": "Super Nintendo Game ROM",
    ".WDGT": "Dashboard Widget",
    ".XAP": "Silverlight Application Package",
    ".SCR": "Windows Screensaver",
    ".DAE": "Digital Asset Exchange File",
    ".IPA": "iOS Application",
    ".DIB": "Device Independent Bitmap File",
    ".SC2REPLAY": "Blizzard StarCraft 2 Replay File",
    ".AHK": "AutoHotkey Script",
    ".SPC": "Software Publisher Certificate File",
    ".RMSKIN": "Rainmeter Skin File",
    ".PARTIAL": "Internet Explorer Partially Downloaded File",
    ".RDP": "Remote Desktop Configuration File",
    ".SQLITEDB": "SQLite Database",
    ".H13": "H&R Block Canada 2013 Tax Return",
    ".PK3": "Quake 3 Engine Game Data File",
    ".BSP": "Quake Engine Game Map File",
    ".SCS": "SimCity Societies Saved Game File",
    ".THEME": "Microsoft Plus! Desktop Theme",
    ".XPI": "Cross-platform Installer Package",
    ".NBS": "Minecraft Note Block Studio File",
    ".SIT": "StuffIt Archive",
    ".MKV": "Matroska Video File",
    ".LRF": "Sony Portable Reader File",
    ".001": "Split Archive File",
    ".AVASTLIC": "Avast License File",
    ".CSHTML": "ASP.NET Razor Web Page",
    ".QUICKENDATA": "Quicken Essentials for Mac Data File",
    ".SQLITE": "SQLite Database File",
    ".CEL": "Celestia Script File",
    ".DOC": "Microsoft Word Document",
    ".MST": "Windows Installer Setup Transform File",
    ".MENC": "Windows Mobile Encrypted File",
    ".ROX": "Roxio Project File",
    ".XVA": "XenServer Virtual Appliance File",
    ".OPDOWNLOAD": "Opera Partially Downloaded File",
    ".VDI": "VirtualBox Virtual Disk Image",
    ".MIF": "MapInfo Interchange Format File",
    ".N64": "Nintendo 64 Emulator ROM File",
    ".MPQ": "Blizzard Mo'PaQ File",
    ".OBI": "Outlook RSS Subscription File",
    ".VBOX-EXTPACK": "Oracle VM VirtualBox Extension Pack",
    ".PROP": "Android Build Properties File",
    ".FLAC": "Free Lossless Audio Codec File",
    ".MD": "Markdown Documentation File",
    ".CRP": "Cities: Skylines Colossal Raw Asset Package",
    ".3MF": "3D Manufacturing File",
    ".CLG": "Windows Catalog File",
    ".BZ2": "Bzip2 Compressed File",
    ".IMG": "Macintosh Disk Image",
    ".MA": "Maya Project File",
    ".DOTX": "Word Open XML Document Template",
    ".NKI": "KONTAKT Instrument File",
    ".WEBP": "WebP Image",
    ".FLT": "OpenFlight Scene Description File",
    ".LBL": "Now Contact Label Template",
    ".INF": "Setup Information File",
    ".DWT": "Dreamweaver Webpage Template",
    ".CCD": "CloneCD Disc Image",
    ".INX": "Adobe InDesign Interchange File",
    ".VTF": "Valve Texture File",
    ".CR2": "Canon Raw Image File",
    ".VMDK": "Virtual Machine Disk File",
    ".SVGZ": "Compressed SVG File",
    ".ARW": "Sony Digital Camera Image",
    ".LXO": "Luxology modo 3D Image",
    ".JSON": "JavaScript Object Notation File",
    ".CONF": "Unix Configuration File",
    ".TMX": "Translation Memory Exchange File",
    ".PROPERTIES": "Java Properties File",
    ".VEG": "VEGAS Video Project",
    ".M4R": "iPhone Ringtone File",
    ".NRI": "Nero ISO CD Compilation File",
    ".LIVEUPDATE": "Symantec LiveUpdate File",
    ".UWL": "User Word List File",
    ".WBC": "Webshots Collection File",
    ".ISD": "Flexera InstallShield Dialog Box File",
    ".TLG": "QuickBooks Transaction Log File",
    ".NBA": "Nero BackItUp Archive",
    ".C2R": "Windows Media Center Click-To-Record File",
    ".T08": "TaxCut 2008 Tax Return",
    ".MET": "eMule Resource File",
    ".AFC": "Mass Effect 2 Audio File",
    ".MASSEFFECTSAVE": "Mass Effect Saved Game",
    ".DMSE": "Sound Editor Project File",
    ".DMSA": "Music Disc Creator Project File",
    ".CATPRODUCT": "CATIA V5 Assembly File",
    ".KDC": "Kaspersky Virus Database File",
    ".SC2MAP": "Blizzard StarCraft 2 Map File",
    ".SC2MOD": "Blizzard StarCraft 2 Modification File",
    ".MGT": "Musicnotes Guitar Guru Song File",
    ".FMW": "FME Workbench File",
    ".MDDATA": "iPhone Backup File",
    ".EDJ": "Enlightenment Theme File",
    ".TAX2010": "TurboTax 2010 Tax Return",
    ".VMC": "Windows Virtual Machine Configuration File",
    ".CLS": "LaTeX Document Class File",
    ".CELX": "Celestia Script",
    ".HPT": "HotDocs PDF Template",
    ".ALS": "Ableton Live Set File",
    ".AMXD": "Ableton Max Patch File",
    ".FACEFX": "FaceFX Actor File",
    ".CST": "Manga Studio Story File",
    ".ITMSP": "iTunes Store Package",
    ".SIS.DM": "Ovi Store DRM-Protected Application",
    ".A2L": "ASAP2 ECU Description File",
    ".PCSAV": "Mass Effect 2 Saved Game",
    ".SLP": "SpectraLayers Pro Project",
    ".TT12": "TurboTax Canada 2012 Tax Return",
    ".T12": "At Home 2012 Tax Return",
    ".TRAK": "Traktor Content Pack File",
    ".PJ2": "xPlan Document",
    ".MPKT": "MOPEKS Trial File",
    ".GMW": "Global Mapper Workspace File",
    ".CAPT": "Capito Data File",
    ".SCDOC": "SpaceClaim Document",
    ".XDNA": "DNA Strider Sequence File",
    ".JPEG": "JPEG Image",
    ".GHO": "Norton Ghost Backup File",
    ".MAP": "Quake Engine Map File",
    ".DOCX": "Microsoft Word Open XML Document",
    ".SKP": "SketchUp Document",
    ".DEX": "Dalvik Executable File",
    ".PGN": "Portable Game Notation File",
    ".WEBM": "WebM Video File",
    ".WOFF": "Web Open Font Format File",
    ".HTACCESS": "Apache HTACCESS File",
    ".CSH": "Photoshop Custom Shapes File",
    ".CONTACT": "Windows Contact File",
    ".ITC2": "iTunes Cover Flow Data File 2",
    ".WLMP": "Windows Live Movie Maker Project File",
    ".SIS": "Symbian Installation File",
    ".RMVB": "RealMedia Variable Bit Rate File",
    ".NEF": "Nikon Electronic Format RAW Image",
    ".IWD": "Call of Duty Game Data File",
    ".ADT": "ACT! Document Template",
    ".JPS": "Stereo JPEG Image",
    ".RW2": "Panasonic RAW Image",
    ".EAR": "Java Enterprise Archive File",
    ".BIK": "Bink Video File",
    ".CBZ": "Comic Book Zip Archive",
    ".MXF": "Material Exchange Format File",
    ".FP7": "FileMaker Pro 7+ Database",
    ".MD5": "MD5 Checksum File",
    ".ACROBATSECURITYSETTINGS": "Adobe Acrobat Security Settings File",
    ".BLG": "Windows Binary Performance Log File",
    ".DST": "AutoCAD Sheet Set File",
    ".VSDX": "Visio Drawing",
    ".PUB": "Publisher Document",
    ".VHD": "Virtual PC Virtual Hard Disk",
    ".SM": "StepMania Song File",
    ".PAF.EXE": "PortableApps.com Program File",
    ".PROFILE": "Bash Shell Profile",
    ".MDX": "Extended Media Descriptor File",
    ".ELF": "Executable and Linkable Format File",
    ".ENL": "EndNote Library",
    ".PROTO": "Protocol Buffer File",
    ".GS": "Google Apps Script",
    ".BCD": "Windows Boot Configuration Data File",
    ".MOBI": "Mobipocket eBook",
    ".OCX": "ActiveX Control",
    ".NRG": "Nero CD/DVD Image File",
    ".YML": "YAML Document",
    ".WSDL": "Web Services Description Language File",
    ".BASH_PROFILE": "Bash Interactive Login Shell File",
    ".OBJ": "Wavefront 3D Object File",
    ".RES": "C++ Complied Resource Script",
    ".VDPROJ": "Visual Studio Setup and Deployment Project",
    ".FPF": "IKEA Home Planner File",
    ".MTD": "Musicnotes Digital Sheet Music File",
    ".MARKDOWN": "Markdown Documentation File",
    ".MIDI": "MIDI File",
    ".CDR": "CorelDRAW Image File",
    ".HPP": "C++ Header File",
    ".FBR": "FlashBack Screen Recording",
    ".FCGI": "FastCGI File",
    ".PAS": "Pascal Source File",
    ".IBOOKS": "Multi-Touch iBook",
    ".PMD": "PageMaker Document",
    ".OMF": "Open Media Framework File",
    ".XSD": "XML Schema Definition",
    ".DCF": "DRM Content Format File",
    ".GMK": "GameMaker Project File",
    ".CSPROJ": "Visual Studio C# Project",
    ".WBZ": "Webshots Download Picture File",
    ".APPREF-MS": "Microsoft Application Reference File",
    ".ISE": "InstallShield Express Project File",
    ".DMSM": "VideoWave Movie Project File",
    ".CG": "Cg Program",
    ".PHOTOSLIBRARY": "Photos Library",
    ".PAC": "Proxy Auto-Config File",
    ".AEPX": "After Effects XML Project",
    ".AZW3": "Amazon KF8 eBook File",
    ".ZAP": "Zero Administration Package File",
    ".OGG": "Ogg Vorbis Audio File",
    ".SDB": "SAP2000 Model File",
    ".SNAG": "SnagIt Capture File",
    ".VDF": "AntiVir Virus Definitions File",
    ".VBPROJ": "Visual Studio Visual Basic Project",
    ".CTB": "AutoCAD Color-Based Plot Style File",
    ".CDF": "Computable Document Format File",
    ".XCF": "GIMP Image File",
    ".FS": "Visual F# Source File",
    ".ORIG": "Original File",
    ".CDI": "DiscJuggler Disc Image",
    ".SAT": "ACIS SAT 3D Model File",
    ".CVA": "HP System Software Manager Information File",
    ".TRK": "CompeGPS Land Track File",
    ".!BT": "BitTorrent Incomplete Download File",
    ".CCP": "CopperCube JavaScript File",
    ".MPEG": "MPEG Movie",
    ".LIB": "Generic Data Library",
    ".PLIST": "Mac OS X Property List File",
    ".BSB": "BioShock Saved Game File",
    ".MSP": "Windows Installer Patch",
    ".NC": "Mastercam Numerical Control File",
    ".CHD": "MAME Hard Disk Image",
    ".PEM": "Privacy Enhanced Mail Certificate",
    ".NIB": "Interface Builder User Interface File",
    ".EMX": "eMusic Download File",
    ".DT1": "DTED Level 1 File",
    ".RESX": ".NET Managed Resources File",
    ".PCAST": "iTunes Podcast File",
    ".FTL": "FreeMarker Template File",
    ".ACD-ZIP": "Sony ACID Project With Embedded Media File",
    ".GROUP": "Windows Contacts Group File",
    ".M3U8": "UTF-8 M3U Playlist File",
    ".ERB": "Ruby ERB Script",
    ".OBK": "Backup File",
    ".XEX": "Xbox 360 Executable File",
    ".FDB": "Portfolio Catalog",
    ".WDF": "Workshare Compare DeltaFile",
    ".RX2": "REX2 Audio File",
    ".PTX": "Pro Tools Session File",
    ".WAB": "Windows Address Book",
    ".XLSB": "Excel Binary Spreadsheet",
    ".PLN": "ArchiCAD Project File",
    ".APPLICATION": "ClickOnce Deployment Manifest File",
    ".CAMPROJ": "Camtasia Studio Project",
    ".MDD": "Point Oven Deformation Data File",
    ".GRF": "DPlot Graph File",
    ".PDX": "Adobe Acrobat Index File",
    ".ASD": "Word AutoSave File",
    ".TRX": "Visual Studio Test Results File",
    ".DNG": "Digital Negative Image File",
    ".SWI": "SWiSH Project File",
    ".TS": "Video Transport Stream File",
    ".WFC": "Windows Wireless Network Settings File",
    ".DZM": "DirectorZone Menu Template",
    ".OSM": "OpenStreetMap Map File",
    ".GDOC": "Google Drive Document Link File",
    ".NDX": "dBASE Index File",
    ".FB2": "FictionBook 2.0 File",
    ".SRF": "Sony RAW Image",
    ".VXML": "VoiceXML File",
    ".RVT": "Revit Project File",
    ".AVX": "ArcView Extension File",
    ".BVP": "VodaHost BlueVoda Project File",
    ".ARX": "AutoCAD Runtime Extension File",
    ".QRC": "Qt Resource Collection File",
    ".XBAP": "XAML Browser Application File",
    ".FTM": "FamiTracker Module",
    ".MXS": "Maxwell Studio Scene File",
    ".JBC": "Jam STAPL Byte-Code File",
    ".HFD": "HotDocs Form Document",
    ".AZW4": "Amazon Print Replica eBook",
    ".FCDT": "FormsCentral Design Template",
    ".FBX": "Autodesk FBX Interchange File",
    ".TRP": "HD Video Transport Stream",
    ".SESX": "Adobe Audition Session File",
    ".FM": "FrameMaker Document",
    ".XAR": "Xara Xtreme Drawing",
    ".RDF": "Resource Description Framework File",
    ".BUNDLE": "Mac OS X Application Bundle",
    ".VCPROJ": "Visual C++ Project File",
    ".MXD": "ArcGIS Map Document",
    ".USR": "SmartMusic Custom File",
    ".MB": "Maya Binary Project File",
    ".STL": "Stereolithography File",
    ".PSH": "Photodex Slide Show",
    ".CDB": "Symbian Phonebook Database",
    ".IDML": "Adobe InDesign Markup Language File",
    ".H": "C/C++/Objective-C Header File",
    ".PFC": "AOL Personal File Cabinet",
    ".RAM": "Real Audio Metadata File",
    ".DWF": "Design Web Format File",
    ".GEM": "RubyGems Package",
    ".RNS": "Reason Song File",
    ".XHTM": "Extensible Hypertext Markup Language Document",
    ".PS1XML": "Windows PowerShell Display Configuration File",
    ".AS3PROJ": "FlashDevelop ActionScript 3 Project File",
    ".B3D": "Blitz3D Entity Model File",
    ".ALE": "Avid Log Exchange File",
    ".DTX": "Documented LaTeX File",
    ".A2C": "Alice Object File",
    ".REXX": "Rexx Source File",
    ".PRG": "Program File",
    ".PPSX": "PowerPoint Open XML Slide Show",
    ".VUE": "Vue Scene File",
    ".SFX": "Windows Self-Extracting Archive",
    ".ACM": "Interplay Audio File",
    ".PCL": "Printer Command Language Document",
    ".ISMV": "IIS Smooth Streaming Video File",
    ".AZW": "Amazon Kindle eBook File",
    ".OLD": "Backup File",
    ".ECM": "ECM Disc Image",
    ".PSP": "PaintShop Pro Image File",
    ".ALZ": "ALZip Archive",
    ".AS": "ActionScript File",
    ".SWP": "Swap File",
    ".MOD": "Camcorder Recorded Video File",
    ".SIB": "Sibelius Score",
    ".LND": "3D Landscape File",
    ".MWF": "MapGuide Author Map Window File",
    ".TAX2009": "TurboTax 2009 Tax Return",
    ".PCR": "PCMark Vantage Benchmark File",
    ".PMF": "ESRI Published Map File",
    ".IDPP": "Adobe InDesign Preflight Profile",
    ".MDINFO": "iPhone Backup Information File",
    ".PBXUSER": "Xcode Project User Data File",
    ".MM": "Objective-C++ Source File",
    ".JSPF": "Java Server Page Fragment",
    ".QVD": "QlikView Data File",
    ".OSDX": "Search Connector Description File",
    ".CDDZ": "ConceptDraw PRO Document",
    ".JNT": "Windows Journal File",
    ".ENC": "Encoded File",
    ".ODP": "OpenDocument Presentation",
    ".PLS": "Multimedia Playlist File",
    ".FRM": "MySQL Database Format File",
    ".CPT": "Corel PHOTO-PAINT Image",
    ".BIF": "BioWare Infinity Engine File",
    ".MWB": "MySQL Workbench Document",
    ".EPUB": "Open eBook File",
    ".PDS": "PowerDirector Script File",
    ".AMR": "Adaptive Multi-Rate Codec File",
    ".CVX": "Canvas Drawing File",
    ".PSF": "Photoshop Proof Settings File",
    ".XPS": "XML Paper Specification File",
    ".BASHRC": "Bash Non-Interactive Login Shell File",
    ".INS": "Internet Settings File",
    ".XISE": "Xilinx ISE Project File",
    ".UDK": "Unreal Engine Map File",
    ".TSV": "Tab Separated Values File",
    ".RB": "Ruby Source Code",
    ".ACD": "ACID Project File",
    ".RELS": "Open Office XML Relationships File",
    ".SHX": "AutoCAD Compiled Shape File",
    ".JSF": "Java Script Command File",
    ".BZ": "Bzip Compressed File",
    ".DGN": "MicroStation Design File",
    ".MTS": "AVCHD Video File",
    ".OPML": "Outline Processor Markup Language File",
    ".STP": "STEP 3D CAD File",
    ".IML": "IntelliJ IDEA Module",
    ".DBK": "Sony Ericsson Mobile Phone Backup File",
    ".ADP": "Access Project",
    ".DPR": "Delphi Project",
    ".NZB": "NewzBin Usenet Index File",
    ".MEL": "Maya Embedded Language File",
    ".HDMOV": "QuickTime HD Movie File",
    ".DREAM": "Dream Animated Wallpaper File",
    ".PPF": "Edgecam Pathtrace Part File",
    ".AT3": "ATRAC3 Audio File",
    ".DISC": "Roxio Toast Document",
    ".WLX": "Windows Live Mesh Sync File",
    ".NOMEDIA": "Android No Media File",
    ".AQM": "AlpineQuest Map File",
    ".SBU": "Samsung Backup File",
    ".SSC": "StepMania Song File",
    ".PTB": "Sage 50 Backup File",
    ".CMA": "Coach Activity File",
    ".DBX": "Outlook Express E-mail Folder",
    ".WS": "Windows Script",
    ".P12": "Personal Information Exchange File",
    ".NBU": "Nokia Phone Backup File",
    ".DSN": "Database Source Name File",
    ".PS1": "Windows PowerShell Cmdlet File",
    ".V": "Verilog Source Code File",
    ".EMZ": "Windows Compressed Enhanced Metafile",
    ".ODS": "OpenDocument Spreadsheet",
    ".WAR": "Java Web Archive",
    ".VWX": "Vectorworks Design File",
    ".GML": "Geography Markup Language File",
    ".OMG": "Image File",
    ".DOT": "Word Document Template",
    ".QDF": "Quicken Data File",
    ".NOTEBOOK": "SMART Notebook File",
    ".AA3": "ATRAC Audio File",
    ".TOC": "Eudora Table of Contents",
    ".TIX": "DivX Video Download Activation File",
    ".MXL": "Compressed MusicXML File",
    ".SBN": "ESRI Spatial Binary File",
    ".MPO": "Multi Picture Object File",
    ".CGFX": "CgFX Shader File",
    ".BUP": "DVD IFO Backup File",
    ".EFX": "eFax Document",
    ".CHR": "3ds Max Characters File",
    ".VBOX": "Oracle VM VirtualBox Settings File",
    ".VRO": "DVD Video Recording Format",
    ".ALX": "ActiveX Layout Control File",
    ".NUMBERS": "Numbers Spreadsheet File",
    ".CDD": "ConceptDraw PRO Document",
    ".BGL": "Flight Simulator Scenery File",
    ".CDA": "CD Audio Track Shortcut",
    ".JNLP": "Java Web Start File",
    ".AXD": "ASP.NET Web Handler File",
    ".3DR": "3DMark Results File",
    ".DZP": "DirectorZone Particle Effect File",
    ".PS": "PostScript File",
    ".MNG": "Multiple Network Graphic",
    ".LIC": "Software License File",
    ".ICA": "Citrix ICA File",
    ".CPI": "AVCHD Video Clip Information File",
    ".CSF": "Adobe Color Settings File",
    ".MAT": "MATLAB MAT-File",
    ".MPX": "Microsoft Project Exchange File",
    ".TDL": "Tab Delineated Format File",
    ".CAF": "Core Audio File",
    ".OVF": "Open Virtualization File",
    ".STX": "Pinnacle Studio Project File",
    ".OEACCOUNT": "Windows Mail Account File",
    ".EMP": "eMusic Music Download File",
    ".II": "IconWorkshop Extended Information File",
    ".JDB": "Symantec Endpoint Protection Update File",
    ".UTZ": "UIQ Theme Package",
    ".PRO": "Qt Project File",
    ".SC45": "SuperCard Project File",
    ".WWF": "World Wide Fund Non-Printable Document",
    ".XPJ": "RoboHelp HTML Project File",
    ".WCX": "RemoteApp and Desktop Connections Configuration File",
    ".NB0": "Device Boot Loader Image",
    ".PBXPROJ": "Xcode Project Data File",
    ".NWF": "Navisworks File Set",
    ".T11": "At Home 2011 Tax Return",
    ".DSF": "DAZ Studio Asset File",
    ".DPROJ": "Delphi Project",
    ".SQF": "ArmA Script File",
    ".WB2": "Webshots Picture File",
    ".LOGICX": "Logic Pro Project",
    ".HLP": "Windows Help File",
    ".SHP": "ESRI Shapefile",
    ".PRX": "Windows Media Profile File",
    ".DASH": "MPEG-DASH Video File",
    ".MDI": "Microsoft Document Imaging File",
    ".TGZ": "Gzipped Tar File",
    ".CATPART": "CATIA V5 Part File",
    ".STM": "Exchange Streaming Media File",
    ".OFX": "Open Financial Exchange File",
    ".XVID": "Xvid-Encoded Video File",
    ".OGV": "Ogg Video File",
    ".MOI": "MOI Video File",
    ".IN": "Input File",
    ".DRW": "Drawing File",
    ".PRC": "Mobipocket eBook File",
    ".M2P": "MPEG-2 Program Stream File",
    ".RP": "Axure RP Project File",
    ".M4B": "MPEG-4 Audiobook File",
    ".FXG": "Flash XML Graphics File",
    ".XFD": "XFD File",
    ".SLX": "MathWorks Simulink Model File",
    ".3DC": "iGO 3D Building File",
    ".MPP": "Microsoft Project File",
    ".VSD": "Visio Drawing File",
    ".SRC": "Source Code",
    ".BSF": "Blu-ray AVC Video File",
    ".ABM": "Photo Album",
    ".UCCAPILOG": "Microsoft UCC API Log File",
    ".VDB": "Symantec Virus Database File",
    ".PPM": "Portable Pixmap Image File",
    ".F4V": "Flash MP4 Video File",
    ".NMF": "ArcGIS Explorer Map File",
    ".LIT": "eBook File",
    ".SID": "MrSID Image",
    ".GSLIDES": "Google Drive Presentation Link File",
    ".PICTCLIPPING": "Picture Clipping File",
    ".XLTM": "Excel Open XML Macro-Enabled Spreadsheet Template",
    ".CP": "Xcode C++ Source File",
    ".STE": "Dreamweaver Site Settings File",
    ".R3D": "REDCODE Video File",
    ".TWB": "Tableau Workbook File",
    ".GCW": "Microsoft Mathematics Worksheet",
    ".IBA": "iBooks Author Document",
    ".MJK": "Question File",
    ".T2D": "TouchDraw Document",
    ".JSPX": "XML Java Server Page",
    ".ARC": "Symbian OS Backup File",
    ".ADF": "ESRI ArcInfo Binary Grid Format",
    ".XLL": "Excel Add-In File",
    ".PLT": "AutoCAD Plotter Document",
    ".SVF": "Serial Vector Format File",
    ".ISM": "IIS Smooth Streaming Manifest File",
    ".QXP": "QuarkXPress Project File",
    ".DVR-MS": "Microsoft Digital Video Recording",
    ".DCP": "Adobe DNG Camera Profile",
    ".AA": "Audible Audio Book File",
    ".OUT": "Output File",
    ".VMX": "VMware Configuration File",
    ".SQZ": "Squeeze Project File",
    ".WML": "Wireless Markup Language File",
    ".XSL": "XML Style Sheet",
    ".FPBF": "Mac OS X Burn Folder",
    ".NRA": "Nero Audio Compilation",
    ".XFDL": "XFDL File",
    ".WIZ": "Microsoft Wizard File",
    ".PTZ": "E-Transcript Bundle File",
    ".FSPROJ": "Visual F# Project File",
    ".DXE": "AutoCAD Data Extraction Template",
    ".QXB": "QuarkXPress Book File",
    ".XQ": "XQuery File",
    ".LDT": "Eulumdat Formatted Luminaire Data File",
    ".PBJ": "Pixel Bender Bytecode File",
    ".QB2011": "QuickBooks 2011 File",
    ".TAX2011": "TurboTax 2011 Tax Return",
    ".ADCP": "Adobe Device Central Project File",
    ".MSHC": "Microsoft Help Container File",
    ".QB2013": "QuickBooks 2013 File",
    ".T13": "H&R Block 2013 Tax Return",
    ".TCD": "TurboCAD Mac Deluxe Drawing",
    ".GDT": "gretl Datafile",
    ".PPTM": "PowerPoint Open XML Macro-Enabled Presentation",
    ".EXP": "Symbols Export File",
    ".DIVX": "DivX-Encoded Movie File",
    ".HDP": "HD Photo File",
    ".DSS": "Digital Speech Standard File",
    ".SPS": "SPSS Program File",
    ".JP2": "JPEG 2000 Core Image File",
    ".PST": "Outlook Personal Information Store File",
    ".UCF": "WebEx Media File",
    ".MCDX": "Mathcad Prime Document",
    ".CPR": "Cubase Project",
    ".U3D": "Universal 3D File",
    ".BKP": "Backup File",
    ".GCF": "Game Cache File",
    ".XLTX": "Excel Open XML Spreadsheet Template",
    ".JRPRINT": "JasperReports Print File",
    ".MWX": "MapGuide Author Map Window XML File",
    ".ORA": "Oracle Database Configuration File",
    ".SNAGPROJ": "Snagit Project File",
    ".TBK": "ToolBook File",
    ".PRJ": "Project File",
    ".IDW": "Inventor Drawing",
    ".DSB": "Wondershare DVD Slideshow Builder Project",
    ".JPX": "JPEG 2000 Image File",
    ".ACSM": "Adobe Content Server Message File",
    ".FMP12": "FileMaker Pro 12 Database",
    ".BOOK": "FrameMaker Book File",
    ".FREEWAY": "Freeway Document",
    ".DCM": "DICOM Image",
    ".PET": "Puppy Linux Install Package",
    ".IPT": "Inventor Part File",
    ".WINDOWSLIVECONTACT": "Windows Live Contacts File",
    ".MONTAGE": "Montage Screenplay File",
    ".ERF": "BioWare Entity Resource File",
    ".GRAFFLE": "OmniGraffle Drawing",
    ".PVR": "POWERVR Texture File",
    ".QBO": "QuickBooks Online Bank Statement File",
    ".QVW": "QlikView Document",
    ".IMA": "Sage ACT! Email Message",
    ".QB2014": "QuickBooks 2014 File",
    ".PLAYGROUND": "Xcode Playground File",
    ".ENEX": "Evernote Archive",
    ".HYPE": "Hype Document",
    ".MMP": "Symbian Project Specification File",
    ".PPP": "Serif PagePlus Document",
    ".DLX": "DIALux Document",
    ".DAZ": "DAZ Studio 3D Scene",
    ".SEQ": "PowerTracks Pro Audio Project File",
    ".DPX": "Digital Picture Exchange File",
    ".QPW": "Quattro Pro Spreadsheet",
    ".WEBARCHIVE": "Safari Web Archive",
    ".CRD": "Windows CardSpace File",
    ".GSHEET": "Google Drive Spreadsheet Link File",
    ".MDJ": "StarUML Model File",
    ".BDM": "AVCHD Information File",
    ".ASMX": "ASP.NET Web Service File",
    ".APE": "Monkey's Audio Lossless Audio File",
    ".SDR": "SmartDraw Drawing",
    ".SMIL": "SMIL Presentation File",
    ".PGP": "PGP Security Key",
    ".TPS": "Clarion TopSpeed Data File",
    ".LWS": "LightWave 3D Scene File",
    ".IAM": "Inventor Assembly File",
    ".MS": "3ds Max Script File",
    ".THMX": "Office 2007 Theme File",
    ".MOHO": "Moho Animation Project",
    ".PXM": "Pixelmator Image File",
    ".AMZ": "Amazon MP3 Downloader File",
    ".ID2": "Windows Live Messenger Emoticon File",
    ".GPI": "Garmin Point of Interest File",
    ".VBT": "Spyware Doctor Temporary Scan File",
    ".MASSEFFECTPROFILE": "Mass Effect Player Profile",
    ".HME": "Windows Mobile Theme File",
    ".DVDMEDIA": "RipIt DVD Package",
    ".FSX": "Visual F# Script File",
    ".VTM": "Visual Tool Markup Language Document",
    ".BR6": "Bryce 6 Scene File",
    ".T10": "At Home 2010 Tax Return",
    ".ASY": "Asymptote Module",
    ".TT10": "TurboTax Canada 2010 Tax Return",
    ".AVP": "Avid Project File",
    ".SISX.DM": "Nokia Ovi Store DRM-Protected Application",
    ".OTRKEY": "OnlineTvRecorder Encoded Video File",
    ".MMF": "Meal-Master Recipe File",
    ".FMC": "FormConnect Form File",
    ".NGRR": "Guitar Rig Preset",
    ".MDSX": "MEGA Saved Session",
    ".FPPX": "Microsoft Fresh Paint Painting File",
    ".SPV": "SPSS Output Document",
    ".WTV": "Windows Recorded TV Show File",
    ".NWD": "Navisworks Document",
    ".MCD": "Mathcad Document",
    ".ATT": "Web Form Post Data File",
    ".EXIF": "Exchangeable Image Information File",
    ".CDX": "ChemDraw Exchange File",
    ".SKM": "SketchUp Materials File",
    ".IMOVIEPROJ": "iMovie Project File",
    ".ATOM": "Atom Syndication Format",
    ".EDL": "Edit Decision List File",
    ".ICC": "ICC Profile",
    ".BR5": "Bryce 5 Scene File",
    ".QFX": "Quicken Financial Exchange File",
    ".SCF": "Windows Explorer Command",
    ".PTF": "Pro Tools 7 Session File",
    ".AFX": "Auto FX PhotoGraphic Edges Image",
    ".FXP": "Adobe Flex Project File",
    ".LWO": "LightWave 3D Object File",
    ".SCN": "Age of Mythology Scenario File",
    ".CPG": "Manga Studio Page File",
    ".TAX2013": "TurboTax 2013 Tax Return",
    ".XFDF": "Adobe Acrobat XFDF File",
    ".XDB": "Symantec Virus Database File",
    ".FCPROJECT": "Final Cut Pro X Project File",
    ".NBD": "NovaBACKUP File",
    ".TCP": "TurboCAD Mac Pro Drawing",
    ".MSO": "Inline E-mail Attachment",
    ".PCH": "Precompiled Header File",
    ".WB3": "Corel Quattro Pro 7 and 8 File",
    ".AZW1": "Amazon Topaz eBook",
    ".BBPROJECTD": "BBEdit Project Document",
    ".MPH": "Photostory Deluxe Project",
    ".RKT": "Racket Source Code File",
    ".PCAPNG": "Pcap-NG Packet Capture File",
    ".QBW": "QuickBooks Data File",
    ".SND": "Sound File",
    ".TCW": "TurboCAD Drawing File",
    ".VDX": "Visio Drawing XML File",
    ".CGM": "Computer Graphics Metafile",
    ".TRS": "Rosetta Stone Language Data File",
    ".POD": "Perl POD File",
    ".BMS": "BeatMania Song File",
    ".EDRW": "SolidWorks eDrawings File",
    ".WGT": "Opera Widget File",
    ".DT2": "Windows Live Messenger Emoticon Image File",
    ".IPX": "IPIX Image",
    ".T09": "At Home 2009 Tax Return",
    ".DMSP": "PhotoSuite Project File",
    ".STORYMILL": "StoryMill Project File",
    ".SDEF": "AppleScript Dictionary Document",
    ".PSM1": "Windows PowerShell Script Module File",
    ".FMV": "FME Desktop Viewspace File",
    ".HFT": "HotDocs Form Template",
    ".DCPROJ": "Dashcode Project",
    ".MXI": "Maxwell Image",
    ".QB2012": "QuickBooks 2012 File",
    ".GROUPPROJ": "Delphi Project Group File",
    ".SPUB": "Swift Publisher Document",
    ".MOX": "Montax Imposer Template Document",
    ".GFAR": "Greenfoot Archive",
    ".PJM": "xPlan Model",
    ".TT13": "TurboTax Canada 2013 Tax Return",
    ".RBW": "Ruby Script",
    ".XTODVD": "ConvertXtoDVD Project File",
    ".OV2": "TomTom Points of Interest Database",
    ".XSLT": "XSL Transformation File",
    ".EPW": "EnergyPlus Weather Data File",
    ".R": "Rez Source Code File",
    ".VF": "VEGAS Movie Studio Project File",
    ".CDMM": "ConceptDraw MINDMAP Document",
    ".DRA": "OrCAD Drawing File",
    ".HPD": "HotDocs PDF Document",
    ".AVS": "AviSynth Script File",
    ".CKD": "Kubotek Design Container",
    ".QB2009": "QuickBooks 2009 File",
    ".RCPROJECT": "iMovie '08 Project",
    ".WKS": "Works Spreadsheet",
    ".DBB": "Skype User Information File",
    ".HPL": "HP-GL Plotter File",
    ".DBA": "Palm Datebook Backup File",
    ".NTP": "Natron Project File",
    ".FUN": "Cubify Invention File",
    ".CTF": "AVG Update Control File",
    ".WIXPROJ": "WiX Project File",
    ".HCP": "HydroCAD Project File",
  },
};
